#!/usr/bin/env bash
#
# Simple wrapper for composer with DockerComposeDrupal.
#
# Depends on:
#  docker
#  DockerComposeDrupal

_SOURCE="${BASH_SOURCE[0]}"
while [ -h "$_SOURCE" ]; do # resolve $_SOURCE until the file is no longer a symlink
  _DIR="$( cd -P "$( dirname "$_SOURCE" )" && pwd )"
  _SOURCE="$(readlink "$_SOURCE")"
  [[ $_SOURCE != /* ]] && _SOURCE="$_DIR/$_SOURCE" # if $_SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
_DIR="$( cd -P "$( dirname "$_SOURCE" )" && pwd )"

if [ ! -f $_DIR/helpers/common.sh ]; then
  echo -e "[ERROR] Missing helpers/common.sh file."
  exit 1
fi
source $_DIR/helpers/common.sh

_docker_exec_noi_u mkdir -p /.composer/cache
_docker_exec_noi_u chown -R ${LOCAL_UID}: /.composer

_docker_exec \
  composer --working-dir="/var/www/localhost" "$@"
