#!/usr/bin/env bash
# ____   ____   ____                         _
# |  _ \ / ___| |  _ \ _ __ _   _ _ __   __ _| |
# | | | | |     | | | | '__| | | | '_ \ / _  | |
# | |_| | |___  | |_| | |  | |_| | |_) | (_| | |
# |____/ \____| |____/|_|   \__,_| .__/ \__,_|_|
#                               |_|
#
# Helper to run postgres dump/restore, part of Docker Compose Drupal project.
# Based on Bash simple Boilerplate.
# https://github.com/Mogtofu33/docker-compose-drupal
#
# Usage:
#   pgsql dump | restore
#
# Depends on:
#  docker
#
# Bash Boilerplate: https://github.com/alphabetum/bash-boilerplate
# Bash Boilerplate: Copyright (c) 2015 William Melody • hi@williammelody.com

_SOURCE="${BASH_SOURCE[0]}"
while [ -h "$_SOURCE" ]; do # resolve $_SOURCE until the file is no longer a symlink
  _DIR="$( cd -P "$( dirname "$_SOURCE" )" && pwd )"
  _SOURCE="$(readlink "$_SOURCE")"
  [[ $_SOURCE != /* ]] && _SOURCE="$_DIR/$_SOURCE" # if $_SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
_DIR="$( cd -P "$( dirname "$_SOURCE" )" && pwd )"

if [ ! -f $_DIR/helpers/common.sh ]; then
  echo -e "Missing helpers/common.sh file."
  exit 1
fi
source $_DIR/helpers/common.sh

###############################################################################
# Help
###############################################################################

# _print_help()
#
# Usage:
#   _print_help
#
# Print the program help information.
_print_help() {
  cat <<HEREDOC
  ____   ____   ____                         _
 |  _ \ / ___| |  _ \ _ __ _   _ _ __   __ _| |
 | | | | |     | | | | '__| | | | '_ \ / _  | |
 | |_| | |___  | |_| | |  | |_| | |_) | (_| | |
 |____/ \____| |____/|_|   \__,_| .__/ \__,_|_|
                                |_|

Helper to dump and restore PGSQL db with pg_dump and pg_restore.

Usage:
  ${_ME} [dump | restore | list]
  ${_ME} -h | --help

Options:
  -h --help  Show this screen.
HEREDOC
}

_DUMP_FILE="dump.pg_dump"

###############################################################################
# Program Functions
###############################################################################

_dump() {
  _DUMP_FILE="dump_${_NOW}.pg_dump"
  _docker_exec \
    --user "${PGSQL_USER}" \
    "${PROJECT_CONTAINER_PGSQL}" \
      pg_dump -d "${POSTGRES_DB}" -U "${PGSQL_USER}" -hlocalhost -Fc -c -b -v -f ${PROJECT_CONTAINER_DUMP}/${_DUMP_FILE} \
      --exclude-table-data '*.cache*' --exclude-table-data '*.cachetags*' \
      --exclude-table-data '*.watchdog*' --exclude-table-data '*.node_access*' \
      --exclude-table-data '*.search_api_db_*' --exclude-table-data '*.sessions*' \
      --exclude-table-data '*.sessions*' --exclude-table-data '*.webprofiler*'

  echo -e "Database dump saved to ${_DUMP_FILE}"
}

_restore() {
  _select_dump
  echo -e "Restoring $_DUMP_FILE..."
  if [ ! -z "$_DUMP_FILE" ]; then
    _docker_exec \
      --user "${PGSQL_USER}" \
      "${PROJECT_CONTAINER_PGSQL}" \
        dropdb --if-exists "${POSTGRES_DB}"
    _docker_exec \
      --user "${PGSQL_USER}" \
      "${PROJECT_CONTAINER_PGSQL}" \
        createdb -e --owner="${PGSQL_USER}" "${POSTGRES_DB}"
    _docker_exec \
      --user "${PGSQL_USER}" \
      "${PROJECT_CONTAINER_PGSQL}" \
        psql -e -d ${POSTGRES_DB} -c "GRANT ALL ON database ${POSTGRES_DB} TO ${PGSQL_USER}"
    _docker_exec \
      --user "${PGSQL_USER}" \
      "${PROJECT_CONTAINER_PGSQL}" \
        pg_restore -h localhost -p 5432 --no-owner --role="${PGSQL_USER}" -U "${PGSQL_USER}" -d "${POSTGRES_DB}" -v ${PROJECT_CONTAINER_DUMP}/${_DUMP_FILE}
  fi
}

_list_dump() {
  echo -e "Available dump files:"
  _docker_exec "${PROJECT_CONTAINER_PGSQL}" ls -lah "${PROJECT_CONTAINER_DUMP}"
}

_ensure_dir() {
  # No interactive, ensure permissions.
  $_DOCKER exec $tty "${PROJECT_CONTAINER_PGSQL}" chown -R ${PGSQL_USER_ID} "${PROJECT_CONTAINER_DUMP}"
}

_select_dump() {

  _DUMPS=$($_DOCKER exec --user "${PGSQL_USER}" "${PROJECT_CONTAINER_PGSQL}"  ls "${PROJECT_CONTAINER_DUMP}")
  _DUMPS=(`echo $_DUMPS | sed 's/ /\n/g'`)

  echo -e "Select a dump file:"
  select opt in "${_DUMPS[@]}" "Cancel"; do
    case $opt in
      *.pg_dump)
        _DUMP_FILE=$opt
        break
        ;;
      "Cancel")
        echo "You chose to cancel"
        _DUMP_FILE=""
        break
        ;;
      *)
        echo "This is not a number"
        ;;
    esac
  done
}

###############################################################################
# Main
###############################################################################

# _main()
#
# Usage:
#   _main [<options>] [<arguments>]
#
# Description:
#   Entry point for the program, handling basic option parsing and dispatching.
_main() {

  _check_dependencies_docker
  _set_container_pgsql

  # Run actions.
  if [[ "${1:-}" =~ ^list$ ]]; then
    _list_dump
  elif [[ "${1:-}" =~ ^dump$ ]]; then
    _ensure_dir
    _dump
  elif [[ "${1:-}" =~ ^restore$ ]]; then
    _restore
  else
    _print_help
  fi
}

# Call `_main` after everything has been defined.
_main "$@"

